import type { Metadata } from "next";
import "./globals.css";
// import { Rubik } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";

// const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Navmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      /> */}
{/*  ${rubik.className} */}
      <body
        className={`antialiased`}
      >
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
